// This file was generated by the IntelXchange Meta Model Manager.
// Domain/Version: DwhExporter/1.0.0
// Meta Model Manager version: 1.1.0.SNAPSHOT

package com.sabre.ix.application;

import com.sabre.ix.application.input.BookingSelector;
import com.sabre.ix.application.output.ExportDBConnectionHandler;
import com.sabre.ix.client.context.Context;
import com.sabre.ix.client.context.ContextFactory;
import org.apache.log4j.Logger;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

public class Main {
    private static final Logger log = Logger.getLogger(Main.class);

    public static void main(String args[]) throws IOException, ClassNotFoundException, IllegalAccessException, InstantiationException {
        Context ixCtx = ContextFactory.createContext();

        File exportInterfaceProperties = new File("exportInterface.properties");
        if(!exportInterfaceProperties.exists()) {
            exportInterfaceProperties = new File("config/exportInterface.properties");
        }
        log.info("Loading exporter properties from file: " + exportInterfaceProperties.getAbsolutePath());
        Properties p = new Properties();
        p.load(new FileInputStream(exportInterfaceProperties));

        DataWarehouseExporter exporter = new DataWarehouseExporter();

        Class exportTargetImplementationClass = Class.forName((String)p.get("DWHExporter_OutputClass"));
        ExportDBConnectionHandler exportDBConnectionHandler = (ExportDBConnectionHandler) exportTargetImplementationClass.newInstance();

        Class bookingSelectorImplementationClass = Class.forName((String)p.get("DWHExporter_BookingSelectorClass"));
        BookingSelector bookingSelector = (BookingSelector) bookingSelectorImplementationClass.newInstance();
        bookingSelector.setProperties(p);

        // Set up staging export session
        exportDBConnectionHandler.setDriver(p.getProperty("DWHExporter_Driver"));
        exportDBConnectionHandler.setConnectionString(p.getProperty("DWHExporter_ConnectionString"));
        exportDBConnectionHandler.setUserName(p.getProperty("DWHExporter_UserName"));
        exportDBConnectionHandler.setPassword(p.getProperty("DWHExporter_Password"));

        exporter.setExportDBConnectionHandler(exportDBConnectionHandler);
        exporter.setNumberOfThreads(Integer.parseInt(p.getProperty("DWHExporter_NumberOfThreads")));
        exporter.setContext(ixCtx);
        exporter.setBookingSelector(bookingSelector);


        try {
            exporter.run();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
